### ISSUE TITLE
为什么GlideImageView屏蔽了父View的点击事件？

### ISSUE THREAD

**Issue by umeitime** [sfsheng0322/GlideImageView#10]
Item点击事件被imageview拦截掉了。点击imageview无法跳转~

**Comment by gogolq** [comment]
我也遇到。。。求解救。。

**Comment by sfsheng0322** [comment]
图片的触摸效果确实拦截了点击事件，最新版V1.1.0默认没有触摸效果siv_shape_type默认为none，如需设置触摸效果、圆角或圆形请设置siv_shape_type为1:rectangle或2:circle，谢谢啦
