### ISSUE TITLE
DisplayUtil导致内存泄露

### ISSUE THREAD

**Issue by umeitime** [sfsheng0322/GlideImageView#12]
DisplayUtil 里面的windowManager 是静态的 会引起内存泄露

**Comment by umeitime** [comment]
DisplayMetrics dm = context.getResources().getDisplayMetrics();
return dm.widthPixels;  获取图片宽度这样写也可以。

**Comment by umeitime** [comment]
DisplayMetrics dm = context.getResources().getDisplayMetrics();
        return dm.widthPixels;  获取屏幕宽度这样写也可以！

**Comment by sfsheng0322** [comment]
恩，改一下，context.getApplicationContext()，蟹蟹
