### ISSUE TITLE
如何设置缓存地址，RecycleViewActivity 页面滑动，发生图片位置错乱

### ISSUE THREAD

**Issue by yongchao1210** [sfsheng0322/GlideImageView#14]
如题，如何设置本地缓存位置
如何不启用图片点击效果。。
在运行实例的时候RecycleViewActivity，RecyclerView列表中的图片，在来回滑动的时候，发生位置错乱的情况

**Comment by sfsheng0322** [comment]
欢迎使用V2.0.0版本
