### ISSUE TITLE
添加依赖报错

### ISSUE THREAD

**Issue by DaiFalin** [sfsheng0322/GlideImageView#20]
Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (3.0.1) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by a237112263** [comment]
我也是

**Comment by sfsheng0322** [comment]
欢迎使用V2.0.0版本
