### ISSUE TITLE
1.2.0的版本运行Sample  gIf不动。

### ISSUE THREAD

**Issue by DarkSherlock** [sfsheng0322/GlideImageView#32]
请问作者，1.2.0相比1.1.0做了哪些改动。1.1.0的sample，GildeImageView和普通的Imageview都能正常加载Gif，但是1.2.0的GlideImageView加载Gif无论是从网络还是本地，都无法动起来，但是Imageview用
 GlideImageLoader.create(image32).load(gif1, new RequestOptions());这个方法还是能正常加载显示出来。请问问题出在哪里了？

**Comment by DarkSherlock** [comment]
我暂时先用1.1.0的版本，作者看到了，希望能够解答一下，感激不尽！

**Comment by linuxjava** [comment]
gif图必须使用imageview，不能使用它的GlideImageview

**Comment by sfsheng0322** [comment]
去试试V2.0.0版本吧
