### ISSUE TITLE
recyclerview中使用

### ISSUE THREAD

**Issue by KobeBryant824** [sfsheng0322/GlideImageView#8]
在recyclerview的item里使用，会抢占item的点击事件，怎么取消该图片区域触摸

**Comment by umeitime** [comment]
同求啊，我在shapeimageview 注释掉了onTouchEvent 还是不行。

**Comment by sfsheng0322** [comment]
图片的触摸效果确实拦截了点击事件，最新版V1.1.0默认没有触摸效果siv_shape_type默认为none，如需设置触摸效果、圆角或圆形请设置siv_shape_type为1:rectangle或2:circle，谢谢啦
